# Generated by Django 4.0.1 on 2022-03-04 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('second', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Descriptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=250, null=True)),
                ('desc', models.TextField()),
                ('tag', models.ManyToManyField(related_name='tagRelatedName', to='second.Genre')),
            ],
        ),
    ]
