# Generated by Django 4.0.1 on 2022-03-04 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('second', '0002_descriptions'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Genre',
            new_name='Tag',
        ),
    ]
